// Strings used by the service worker and scanner (progress labels, error messages).

export const SWS = {
  sk: {
    scanLoading:   'Načítavam zoznam správ…',
    scanIds:       (f, t) => `Načítané ID: ${f} / ${t}`,
    scanMessages:  (n) => `Skenujem ${n} správ…`,
    scanProgress:  (done, total) => `Skenujem: ${done} / ${total}`,
    scanBody:      (n) => `Hľadám unsub link v tele ${n} správ…`,
    scanBodyProg:  (done, total) => `Telo správ: ${done} / ${total}`,
    scanDone:      (n) => `Hotovo — nájdených ${n} odosielateľov`,
    aborted:       'Skenovanie zrušené',
    unsubProg:     (step, total, name) => `Odhlasovanie ${step} / ${total}: ${name}`,
    archiving:     (name) => `Archivujem maily od: ${name}`,
    filtering:     (name) => `Vytváram filter pre: ${name}`,
    done:          'Hotovo',
    err401:        'Platnosť prihlásenia vypršala — prihláste sa znova',
    err403:        'Nedostatočné oprávnenia — prihláste sa znova',
    err429:        'Gmail API limit — skúste znova o chvíľu',
    errNetwork:    'Chyba siete — skontrolujte pripojenie',
  },
  cs: {
    scanLoading:   'Načítám seznam zpráv…',
    scanIds:       (f, t) => `Načtená ID: ${f} / ${t}`,
    scanMessages:  (n) => `Skenuji ${n} zpráv…`,
    scanProgress:  (done, total) => `Skenuji: ${done} / ${total}`,
    scanBody:      (n) => `Hledám unsub odkaz v těle ${n} zpráv…`,
    scanBodyProg:  (done, total) => `Tělo zpráv: ${done} / ${total}`,
    scanDone:      (n) => `Hotovo — nalezeno ${n} odesílatelů`,
    aborted:       'Skenování zrušeno',
    unsubProg:     (step, total, name) => `Odhlašování ${step} / ${total}: ${name}`,
    archiving:     (name) => `Archivuji maily od: ${name}`,
    filtering:     (name) => `Vytvářím filtr pro: ${name}`,
    done:          'Hotovo',
    err401:        'Platnost přihlášení vypršela — přihlaste se znovu',
    err403:        'Nedostatečná oprávnění — přihlaste se znovu',
    err429:        'Gmail API limit — zkuste znovu za chvíli',
    errNetwork:    'Chyba sítě — zkontrolujte připojení',
  },
  en: {
    scanLoading:   'Loading message list…',
    scanIds:       (f, t) => `Loaded IDs: ${f} / ${t}`,
    scanMessages:  (n) => `Scanning ${n} messages…`,
    scanProgress:  (done, total) => `Scanning: ${done} / ${total}`,
    scanBody:      (n) => `Looking for unsub links in ${n} message bodies…`,
    scanBodyProg:  (done, total) => `Body scan: ${done} / ${total}`,
    scanDone:      (n) => `Done — found ${n} senders`,
    aborted:       'Scan cancelled',
    unsubProg:     (step, total, name) => `Unsubscribing ${step} / ${total}: ${name}`,
    archiving:     (name) => `Archiving emails from: ${name}`,
    filtering:     (name) => `Creating filter for: ${name}`,
    done:          'Done',
    err401:        'Session expired — please sign in again',
    err403:        'Insufficient permissions — please sign in again',
    err429:        'Gmail API rate limit — try again in a moment',
    errNetwork:    'Network error — check your connection',
  },
};

export function sws(lang) {
  return SWS[lang] || SWS.sk;
}
